### ISSUE TITLE
Use php-saml >= 2.10.0

### ISSUE THREAD

**Issue by pitbulk** [MehrAlsNix/zf-saml#1]
[php-saml 2.10.0](https://github.com/onelogin/php-saml/releases/tag/v2.10.0) version.
It includes a security patch that contains extra validations that will prevent signature wrapping attacks and other security improvements.

**Comment by siad007** [comment]
Thanks for using our little module - i have updated the composer dependencies, so it will be possible to use this requirement. I hope to have some much more work on the zf-saml module next week. Feel free to post new issues, if you found anything else. I will try to implement it as soon as possible.
